config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users
  resources :categories
  resources :subcategories
  resources :posts do
    resources :comments
    resources :likes
    resources :dislikes
  end

  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :show, :all
    if user.present?
      can :manage, Post
      can :manage, Like
      can :manage, Dislike
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories
    has_many :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :subcategory
  has_many :comment, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :comment, dependent: :destroy
  has_many :post
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comment.create!(comments_params)

    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comments_params
    params.require(:comment).permit(:user_id, :body, :post_id)
  end
end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController
  before_action :find_post


  def create
    if already_liked_or_disliked?
      flash[:notice] = "You can't like or dislike more than once"
    else
      @author = User.find(@post.user_id)
      @author.karma -= 1
      @author.save!
      @post.dislikes.create!(user_id: current_user.id)
    end

    redirect_to post_path(@post)
  end

  private

  def dislike_params
    params.require(:dislike).permit(:post_id, :user_id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked_or_disliked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists? or Dislike.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  
  def create
    if already_liked_or_disliked?
      flash[:notice] = "You can't like or dislike more than once"
    else
      @author = User.find(@post.user_id)
      @author.karma += 1
      @author.save!
      @post.likes.create!(user_id: current_user.id)
    end

    redirect_to post_path(@post)
  end

  private

  def like_params
    params.require(:dislike).permit(:post_id, :user_id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked_or_disliked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists? or Dislike.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @likes = @post.likes.size
    @dislikes = @post.dislikes.size
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, alert: "Post created!"
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
 
    if @post.update(post_params)
      redirect_to @post, alert: "Post updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path, alert: "Post deleted!"
  end

  private

  def post_params
    params.require(:post).permit(:name, :body, :category_id, :subcategory_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(karma: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="media">
  <% if comment.user.avatar.attached? %>
    <%= image_tag comment.user.avatar.variant(resize: '75x75!') %>
  <% else %>
    <img src="https://image.flaticon.com/icons/svg/747/747376.svg" height="75px" width="75px" ></img>
  <% end %>
  <div class="media-body">
    <h5 class="mt-0"><%= link_to comment.user.username, user_path(comment.user) %>  wrote <%= time_ago_in_words(comment.created_at) %> ago</h5>
    <p><%= comment.body.html_safe %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comment.build] do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
        Your comment:
        <%= f.text_area :body, :class => "tinymce", :rows => 10, :cols => 10 %>
        <%= tinymce %>
    </div>
    
    <%= f.submit %>
<% end %>

app/views/comments/create.js.erb
$("#comments").append("<%= j render @comment %>");
$("#comment_author").val("");
$("#comment_body").val("");

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id, "Category" %></br>
    <%= form.collection_select(:category_id, Category.order(:name), :id, :name, {:prompt => "Choose category"}, {:id => "category_selection"}) %>
  </div>

  <div class="field">
    <%= form.label :subcategory_id, "Subcategory" %></br>
    <%= form.grouped_collection_select(:subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, {:prompt => "Choose subcategory"}, {:id => "subcategory_selection"}) %>
  </div>

  <div class="field">
    <%= form.label :name, "Name" %></br>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :body, "Text" %></br>
    <%= form.text_area :body, :class => "tinymce", :rows => 20, :cols => 10, id: :item_body %>
    <%= tinymce %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </br>
<% end %>

app/views/posts/edit.html.erb
<div class="form">
    <h1>Edit post</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @post, class: "btn btn-primary" %>
    <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
</div>

app/views/posts/index.html.erb
<h1 style="margin: 1%">All posts</h1>
<% if user_signed_in? %>
  <p style="margin: 1%">
      <%= link_to 'New post', new_post_path, class: "btn btn-primary" %>
  </p>
<% end %>

<% @posts.each do |post| %>
  <div class="card" style="margin: 1%">
    <h5 class="card-header"><%= post.user.username %></h5>
    <div class="card-body">
      <h4 class="card-title"><%= post.name %></h4>
      <%= post.body.html_safe %>
      <p style="margin-top: 1%"><%= link_to 'Show', post_path(post), class: "btn btn-primary" %><p>
    </div>
    <div class="card-footer text-muted">
        <%= post.created_at.strftime("%B, %d %Y") %>
    </div>
  </div>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="form">
    <h1>New post</h1>

    <%= render 'form' %>

    <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
</div>

app/views/posts/show.html.erb
<div class="post-section">

  <div class="link-section">
    <% if user_signed_in? and current_user.id == @post.user_id %>
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %>
      <%= link_to 'Delete', post_path(@post), method: :delete,
                data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <% end %>
  </div>

  <h1><%= @post.name %></h1>

  <p><%= @post.body.html_safe %></p>

  <p>
      <strong>Author</strong>
      <%= @post.user.username %>
  </p>
  
  <div class="likes-and-dislikes">
    <% if user_signed_in? %>
      <div class="likes">
        <%= link_to '+', post_likes_path(@post), method: :post, class: "btn btn-success"%>
      </div>
    <% else %>
      <div class="likes">
        <button type="button" class="btn btn-success" disabled>+</button>
      </div>
    <% end %>
    <div class="likes">
      <p style="position: center"><%= (@likes - @dislikes) %></p>
    </div>
    <% if user_signed_in? %>
      <div class="likes">
        <%= link_to '-', post_dislikes_path(@post), method: :post, class: "btn btn-danger" %>
      </div>
    <% else %>
      <div class="likes">
        <button type="button" class="btn btn-danger" disabled>-</button>
      </div>
    <% end %>
  </div>
</div>

<div class="comment-section">
  <h3>Comments:</h3>
    <ol>
      <%= render @post.comment %>
    </ol>
    <% if user_signed_in? %>
      <h3>Add comment:</h3>
      <%= render 'comments/form' %>
    <% else %>
      <p><%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %> to write comment</p>
    <% end %>
</div>

<div class="link-section">
  <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
</div>

app/views/users/index.html.erb
<div class="user">
    <h1>All users</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Username</th>
                <th>Karma</th>
            </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
                <td>
                    <% if user.avatar.attached? %>
                      <%= image_tag user.avatar.variant(resize: '100x100!'), class: "rounded-circle" %>
                    <% else %>
                      <img src="https://image.flaticon.com/icons/svg/747/747376.svg" height="100px" width="100px" class="rounded-circle"></img>
                    <% end %>
                    <%= link_to user.username, user_path(user) %>
                </td>
                <td><%= user.karma %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
<%= paginate @users %>

app/views/users/show.html.erb
<h1 style="margin: 1%">All posts of <%= @user.username %></h1>

<% @user.post.each do |post| %>
  <div class="card" style="margin: 1% 10% 1% 1%">
    <h5 class="card-header"><%= @user.username %></h5>
    <div class="card-body">
      <h5 class="card-title"><%= post.name %></h5>
      <%= post.body.html_safe %>
      <p style="margin-top: 1%"><%= link_to 'Show', post_path(post), class: "btn btn-primary" %></p>
    </div>
    <div class="card-footer text-muted">
        <%= post.created_at.strftime("%B, %d %Y") %>
    </div>
  </div>
<% end %>