config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users
  resources :categories
  resources :subcategories
  resources :posts do
    resources :comments
    resources :likes
    resources :dislikes
  end

  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can :show, :all
    if user.present?
      can :manage, Post
      can :manage, Like
      can :manage, Dislike
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories
    has_many :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :subcategory
  has_many :comment, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :comment, dependent: :destroy
  has_many :post
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  
  def create
    if already_liked_or_disliked?
      flash[:notice] = "You can't like or dislike more than once"
    else
      @author = User.find(@post.user_id)
      @author.karma += 1
      @author.save!
      @post.likes.create!(user_id: current_user.id)
    end

    redirect_to post_path(@post)
  end

  private

  def like_params
    params.require(:dislike).permit(:post_id, :user_id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked_or_disliked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists? or Dislike.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @likes = @post.likes.size
    @dislikes = @post.dislikes.size
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, alert: "Post created!"
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
 
    if @post.update(post_params)
      redirect_to @post, alert: "Post updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path, alert: "Post deleted!"
  end

  private

  def post_params
    params.require(:post).permit(:name, :body, :category_id, :subcategory_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(karma: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'How it`s done', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <li><%= link_to 'Categories', categories_path, class: "nav-link" %></li>
      </li>
      <li class="nav-item active">
        <li><%= link_to 'Users', users_path, class: "nav-link" %></li>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li role="presentation" class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= image_tag resource.avatar.variant(resize: '30x30!'), class: "rounded-circle" %>
            <% else %>
              <img src="https://image.flaticon.com/icons/svg/747/747376.svg" height="30px" width="30px"></img>
            <% end %>
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to ' Sign up', new_user_registration_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to ' Sign in', new_user_session_path, class: "nav-link" %></li>
      <% end %>
    </ul>
</div>
</nav>